name: E-commerce tests

on:
  push:
    branches: [ "tests" ]

jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Verify files in directory
        run: ls -la

      - name: Build the containers
        run: docker compose -f docker-compose-test.yml up -d

      - name: Run tests in the back-end
        id: exec-tests
        run: |
          echo "tests_result=$(docker exec -t backend-fastecomm /bin/bash tests.sh)" >> $GITHUB_OUTPUT

      - name: Show test results
        env:
          TESTS_RESULT: ${{ steps.exec-tests.outputs.tests_result }}
        run: echo "$TESTS_RESULT"
  
      - name: Check test results
        if: ${{ !contains(steps.exec-tests.outputs.tests_result, 'Tests Ok') }}
        run: exit 1
        continue-on-error: false
  
      - name: Continue if tests passed
        if: ${{ contains(steps.exec-tests.outputs.tests_result, 'Tests Ok') }}
        run: echo "Tests passed successfully."