name: E-commerce tests

on:
  push:
    branches: [ "actions" ]

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Directory
        run: ls -la
      - name: Build the containers
        run: docker compose -f docker-compose-test.yml up -d